from typing import Any, Generic, Iterator, Mapping, TypeVar

_K = TypeVar("_K")
_V = TypeVar("_V")


class frozendict(Mapping[_K, _V], Generic[_K, _V]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __iter__(self) -> Iterator[_K]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: _K) -> _V: ...
